In [1]:
#importar librerias
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from scipy.stats import norm
from scipy import stats
from sklearn.preprocessing import StandardScaler
import warnings

#mostrar las graficas al momento que se piden
%matplotlib inline

In [9]:
datos2011 = pd.read_excel('atus_anual_2011.xlsx')
datos2012 = pd.read_excel('atus_anual_2012.xlsx')
datos2013 = pd.read_excel('atus_anual_2013.xlsx')
datos2014 = pd.read_excel('atus_anual_2014.xlsx')

In [2]:
#leer los archivos
datos2019 = pd.read_excel('atus_anual_2019.xlsx')
datos2020 = pd.read_excel('atus_anual_2020.xlsx')
datos2021 = pd.read_excel('atus_anual_2021.xlsx')
datos2022 = pd.read_excel('atus_anual_2022.xlsx')

In [3]:
#Explorar archivos
#datos2019.shape
#datos2019.head(10)
#datos2019.tail()
#datos2019.dtypes
#datos2019.describe()
#datos2019.columns

In [10]:
#2011
condicion = datos2011['ID_ENTIDAD'] == 20
oaxaca2011 = datos2011[condicion]

oaxaca2011.to_excel('oaxaca2011.xlsx', index=False)

#2012
condicion1 = datos2012['ID_ENTIDAD'] == 20
oaxaca2012 = datos2012[condicion1]

oaxaca2012.to_excel('oaxaca2012.xlsx', index=False)

#2013
condicion2 = datos2013['ID_ENTIDAD'] == 20
oaxaca2013 = datos2013[condicion2]

oaxaca2013.to_excel('oaxaca2013.xlsx', index=False)

#2014
condicion3 = datos2014['ID_ENTIDAD'] == 20
oaxaca2014 = datos2014[condicion3]

oaxaca2014.to_excel('oaxaca2014.xlsx', index=False)

In [4]:
#Eliminar los demas estados
condicion = datos2019['ID_ENTIDAD'] == 20
oaxaca2019 = datos2019[condicion]

oaxaca2019.to_excel('oaxaca2019.xlsx', index=False)

#2020
condicion1 = datos2020['ID_ENTIDAD'] == 20
oaxaca2020 = datos2020[condicion1]

oaxaca2020.to_excel('oaxaca2020.xlsx', index=False)

#2021
condicion2 = datos2021['ID_ENTIDAD'] == 20
oaxaca2021 = datos2021[condicion2]

oaxaca2021.to_excel('oaxaca2021.xlsx', index=False)

#2020
condicion3 = datos2022['ID_ENTIDAD'] == 20
oaxaca2022 = datos2022[condicion3]

oaxaca2022.to_excel('oaxaca2022.xlsx', index=False)

In [11]:
oaxaca2011 = pd.read_excel('oaxaca2011.xlsx')
oaxaca2012 = pd.read_excel('oaxaca2012.xlsx')
oaxaca2013 = pd.read_excel('oaxaca2013.xlsx')
oaxaca2014 = pd.read_excel('oaxaca2014.xlsx')

In [2]:
#Leer los archivos 

oaxaca2019 = pd.read_excel('oaxaca2019.xlsx')
oaxaca2020 = pd.read_excel('oaxaca2020.xlsx')
oaxaca2021 = pd.read_excel('oaxaca2021.xlsx')
oaxaca2022 = pd.read_excel('oaxaca2022.xlsx')

In [ ]:
print(f'COLUMNAS\n2019:{oaxaca2019.columns}\n\n2020:{oaxaca2020.columns}\n\n2021:\n{oaxaca2021.columns}\n\n2022:\n{oaxaca2022.columns}')

In [4]:
#Explorar archivos
oaxaca2019.shape
oaxaca2019.head(10)
oaxaca2019.tail()
oaxaca2019.dtypes
oaxaca2019.describe()
oaxaca2019.columns

(11238, 46)

In [ ]:
oaxaca2011.isnull().any()
oaxaca2012.isnull().any()
oaxaca2013.isnull().any()
oaxaca2014.isnull().any()

In [ ]:
oaxaca2019.isnull().any()
oaxaca2020.isnull().any()
oaxaca2021.isnull().any()
oaxaca2022.isnull().any()

In [16]:
municipios = pd.read_excel('municipios.xlsx')

In [17]:
oa1 = pd.merge(oaxaca2011, municipios, on='ID_MUNICIPIO')
oa1.to_excel('oaxaca2011.xlsx', index=False)

oa2 = pd.merge(oaxaca2012, municipios, on='ID_MUNICIPIO')
oa2.to_excel('oaxaca2012.xlsx', index=False)

oa3 = pd.merge(oaxaca2013, municipios, on='ID_MUNICIPIO')
oa3.to_excel('oaxaca2013.xlsx', index=False)

oa4 = pd.merge(oaxaca2014, municipios, on='ID_MUNICIPIO')
oa4.to_excel('oaxaca2014.xlsx', index=False)

In [9]:
o1 = pd.merge(oaxaca2019, municipios, on='ID_MUNICIPIO')
o1.to_excel('oaxaca2019.xlsx', index=False)

o2 = pd.merge(oaxaca2020, municipios, on='ID_MUNICIPIO')
o2.to_excel('oaxaca2020.xlsx', index=False)

o3 = pd.merge(oaxaca2021, municipios, on='ID_MUNICIPIO')
o3.to_excel('oaxaca2021.xlsx', index=False)

o4 = pd.merge(oaxaca2022, municipios, on='ID_MUNICIPIO')
o4.to_excel('oaxaca2022.xlsx', index=False)

In [18]:
#
oaxaca2011 = pd.read_excel('oaxaca2011.xlsx')
oaxaca2012 = pd.read_excel('oaxaca2012.xlsx')
oaxaca2013 = pd.read_excel('oaxaca2013.xlsx')
oaxaca2014 = pd.read_excel('oaxaca2014.xlsx')
oaxaca2015 = pd.read_excel('oaxaca2015.xlsx')
oaxaca2016 = pd.read_excel('oaxaca2016.xlsx')
oaxaca2017 = pd.read_excel('oaxaca2017.xlsx')
oaxaca2018 = pd.read_excel('oaxaca2018.xlsx')

In [19]:
#juntar los 12 excel
juntar = [oaxaca2011,oaxaca2012,oaxaca2013,oaxaca2014,oaxaca2015, oaxaca2016, oaxaca2017, oaxaca2018,
           oaxaca2019, oaxaca2020, oaxaca2021, oaxaca2022]

datosOaxaca = pd.concat(juntar)
datosOaxaca.to_excel('OaxacaDatos.xlsx', index=False)

In [3]:
datosOaxaca.shape
#datosOaxaca.columns

(80947, 39)

In [2]:
datosOaxaca = pd.read_excel('OaxacaDatos.xlsx')

In [22]:
datosOaxaca.drop(['COBERTURA','ID_ENTIDAD','ID_MUNICIPIO', 'ESTATUS','SEXO','ALIENTO','CINTURON'], axis=1, inplace=True)

datosOaxaca.to_excel('OaxacaDatos.xlsx', index=False)

In [ ]:
datosOaxaca = pd.read_excel('OaxacaDatosDiasFestivos_semana_largo.xlsx')

condicion = (datosOaxaca['URBANA'] == 'Sin accidente en esta zona') & (datosOaxaca['SUBURBANA']
                                                         == 'Sin accidente en esta zona')
dfinal = datosOaxaca[~condicion]

dfinal.to_excel('OaxacaDatosDias.xlsx', index=False)

In [ ]:
import pandas as pd

# Definir los días festivos comunes para cada año de 2011 a 2022
festivos = {
    2011: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-21': 'Natalicio de Benito Juárez',
        '04-21': 'Semana Santa',
        '04-22': 'Semana Santa'
    },
    2012: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-19': 'Natalicio de Benito Juárez',
        '04-05': 'Semana Santa',
        '04-06': 'Semana Santa'
    },
    2013: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-18': 'Natalicio de Benito Juárez',
        '03-28': 'Semana Santa',
        '03-29': 'Semana Santa'
    },
    2014: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-17': 'Natalicio de Benito Juárez',
        '04-17': 'Semana Santa',
        '04-18': 'Semana Santa'
    },
    2015: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-16': 'Natalicio de Benito Juárez',
        '04-02': 'Semana Santa',
        '04-03': 'Semana Santa'
    },
    2016: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-21': 'Natalicio de Benito Juárez',
        '03-24': 'Semana Santa',
        '03-25': 'Semana Santa'
    },
    2017: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-20': 'Natalicio de Benito Juárez',
        '04-13': 'Semana Santa',
        '04-14': 'Semana Santa'
    },
    2018: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-19': 'Natalicio de Benito Juárez',
        '03-29': 'Semana Santa',
        '03-30': 'Semana Santa'
    },
    2019: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-18': 'Natalicio de Benito Juárez',
        '04-18': 'Semana Santa',
        '04-19': 'Semana Santa'
    },
    2020: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-16': 'Natalicio de Benito Juárez',
        '04-09': 'Semana Santa',
        '04-10': 'Semana Santa'
    },
    2021: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-15': 'Natalicio de Benito Juárez',
        '04-01': 'Semana Santa',
        '04-02': 'Semana Santa'
    },
    2022: {
        '01-01': 'Año Nuevo',
        '02-14': 'Día de San Valentín',
        '03-21': 'Natalicio de Benito Juárez',
        '04-14': 'Semana Santa',
        '04-15': 'Semana Santa'
    }
}

# Crear una lista para almacenar los datos
data = []

# Llenar la lista con los días festivos
for year in range(2011, 2022+1):
    for date, fest in festivos[year].items():
        mes, dia = date.split('-')
        data.append([year, int(mes), int(dia), fest])

# Crear el DataFrame
df = pd.DataFrame(data, columns=['ANIO', 'MES', 'ID_DIA', 'DIA_FES'])

# Guardar el DataFrame en un archivo CSV
df.to_csv('dias_festivos_2011_2022.csv', index=False)

In [ ]:
import pandas as pd

# Leer los archivos Excel
df1 = pd.read_excel('Dias.xlsx')
df2 = pd.read_excel('Dias_May-Agosto.xlsx')
df3 = pd.read_excel('dias_festivos_2011_2022.xlsx')

# Combinar los DataFrames
combined_df = pd.concat([df1, df2, df3])

# Ordenar el DataFrame por 'ANIO', 'MES', 'ID_DIA'
combined_df = combined_df.sort_values(by=['ANIO', 'MES', 'ID_DIA'])

# Guardar el DataFrame combinado en un nuevo archivo Excel
combined_df.to_excel('archivo_combinedFestivos.xlsx', index=False)

print("Archivos combinados y guardados exitosamente en 'archivo_combined.xlsx'.")

In [ ]:
import pandas as pd

# Leer los archivos Excel
df1 = pd.read_excel('OaxacaDatos.xlsx')
df_festivos = pd.read_excel('archivo_combinedFestivos.xlsx')


merged_df = pd.merge(df1, df_festivos, on=['ANIO', 'MES', 'ID_DIA'], how='left')

# Reemplazar los valores NaN en la columna 'DIA_FES' con 0
merged_df['DIA_FES'] = merged_df['DIA_FES'].fillna(0)

# Guardar el DataFrame resultante en un nuevo archivo Excel
merged_df.to_excel('OaxacaDatosDiasFestivos.xlsx', index=False)

In [ ]:
import pandas as pd

# Leer el archivo Excel que ya contiene la columna 'DIA_FES'
df = pd.read_excel('OaxacaDatosDiasFestivos.xlsx')

# Función para determinar si es un fin de semana largo
def es_finde_semana_largo(row):
    if (row['DIASEMANA'] == 'viernes' or row['DIASEMANA'] == 'lunes') and row['DIA_FES'] != 0:
        return 1
    else:
        return 0

# Aplicar la función a cada fila del DataFrame
df['Fin_Semana_Largo'] = df.apply(es_finde_semana_largo, axis=1)

# Guardar el DataFrame resultante en un nuevo archivo Excel
df.to_excel('OaxacaDatosDiasFestivos_semana_largo.xlsx', index=False)

In [ ]:
from sqlalchemy import create_engine, Table, Column, Integer, String, MetaData, ForeignKey
import pandas as pd

# Datos de conexión
username = 'edgar'
password = 'mucikaa12'
server = 'localhost'
database = 'accidentes'

# Crear motor de SQLAlchemy
engine = create_engine(f'mysql+pymysql://{username}:{password}@{server}/{database}')

# Crear un objeto MetaData
metadata = MetaData()

# Definir las tablas
tiempo = Table('tiempo', metadata,
    Column('id_tiempo', Integer, primary_key=True, autoincrement=True),
    Column('anio', Integer),
    Column('mes', Integer),
    Column('id_hora', Integer),
    Column('id_minuto', Integer),
    Column('id_dia', Integer),
    Column('diasemana', String(50)),
    Column('dia_fes', String(50)),
    Column('fin_semana_largo', String(50))
)

ubicacion = Table('ubicacion', metadata,
    Column('id_ubicacion', Integer, primary_key=True, autoincrement=True),
    Column('urbana', String(50)),
    Column('suburbana', String(50)),
    Column('nom_municipio', String(100))
)

vehiculo = Table('vehiculo', metadata,
    Column('id_vehiculo', Integer, primary_key=True, autoincrement=True),
    Column('tipaccid', String(50)),
    Column('automovil', Integer),
    Column('campasaj', Integer),
    Column('microbus', Integer),
    Column('pascamion', Integer),
    Column('omnibus', Integer),
    Column('tranvia', Integer),
    Column('camioneta', Integer),
    Column('camion', Integer),
    Column('tractor', Integer),
    Column('ferrocarril', Integer),
    Column('motociclet', Integer),
    Column('bicicleta', Integer),
    Column('otrovehic', Integer)
)

causa_accidente = Table('causa_accidente', metadata,
    Column('id_causa', Integer, primary_key=True, autoincrement=True),
    Column('causaacci', String(100)),
    Column('caparod', String(50))
)

victima = Table('victima', metadata,
    Column('id_victima', Integer, primary_key=True, autoincrement=True),
    Column('id_edad', Integer),
    Column('condmuerto', Integer),
    Column('condherido', Integer),
    Column('pasamuerto', Integer),
    Column('pasaherido', Integer),
    Column('peatmuerto', Integer),
    Column('peatherido', Integer),
    Column('ciclmuerto', Integer),
    Column('ciclherido', Integer),
    Column('otromuerto', Integer),
    Column('otroherido', Integer),
    Column('nemuerto', Integer),
    Column('neherido', Integer)
)

accidente = Table('accidente', metadata,
    Column('id_accidente', Integer, primary_key=True, autoincrement=True),
    Column('id_tiempo', Integer, ForeignKey('tiempo.id_tiempo')),
    Column('id_ubicacion', Integer, ForeignKey('ubicacion.id_ubicacion')),
    Column('id_vehiculo', Integer, ForeignKey('vehiculo.id_vehiculo')),
    Column('id_causa', Integer, ForeignKey('causa_accidente.id_causa')),
    Column('id_victima', Integer, ForeignKey('victima.id_victima')),
    Column('clasacc', String(50))
)

# Crear las tablas en la base de datos
metadata.create_all(engine)

In [ ]:
import pandas as pd
from sqlalchemy import create_engine, MetaData, Table

# Datos de conexión
username = 'edgar'
password = 'mucikaa12'
server = 'localhost'
database = 'accidentes'

# Crear motor de SQLAlchemy
engine = create_engine(f'mysql+pymysql://{username}:{password}@{server}/{database}')

# Leer el archivo Excel
df = pd.read_excel('OaxacaDatosDias.xlsx')

# Crear un objeto MetaData
metadata = MetaData()

# Reflejar las tablas existentes en el objeto MetaData
metadata.reflect(engine)

# Obtener referencias a las tablas
tiempo = metadata.tables['tiempo']
ubicacion = metadata.tables['ubicacion']
vehiculo = metadata.tables['vehiculo']
causa_accidente = metadata.tables['causa_accidente']
victima = metadata.tables['victima']
accidente = metadata.tables['accidente']

# Procesar y registrar los datos en las tablas correspondientes
with engine.begin() as connection:  # Usar el contexto de conexión
    for _, row in df.iterrows():
        # Insertar en la tabla tiempo
        tiempo_insert = {
            'anio': row['ANIO'],
            'mes': row['MES'],
            'id_hora': row['ID_HORA'],
            'id_minuto': row['ID_MINUTO'],
            'id_dia': row['ID_DIA'],
            'diasemana': row['DIASEMANA'],
            'dia_fes': row['DIA_FES'],
            'fin_semana_largo': row['Fin_Semana_Largo']
        }
        result = connection.execute(tiempo.insert().values(tiempo_insert))
        tiempo_id = result.inserted_primary_key[0]

        # Insertar en la tabla ubicacion
        ubicacion_insert = {
            'urbana': row['URBANA'],
            'suburbana': row['SUBURBANA'],
            'nom_municipio': row['NOM_MUNICIPIO']
        }
        result = connection.execute(ubicacion.insert().values(ubicacion_insert))
        ubicacion_id = result.inserted_primary_key[0]

        # Insertar en la tabla vehiculo
        vehiculo_insert = {
            'tipaccid': row['TIPACCID'],
            'automovil': row['AUTOMOVIL'],
            'campasaj': row['CAMPASAJ'],
            'microbus': row['MICROBUS'],
            'pascamion': row['PASCAMION'],
            'omnibus': row['OMNIBUS'],
            'tranvia': row['TRANVIA'],
            'camioneta': row['CAMIONETA'],
            'camion': row['CAMION'],
            'tractor': row['TRACTOR'],
            'ferrocarril': row['FERROCARRI'],
            'motociclet': row['MOTOCICLET'],
            'bicicleta': row['BICICLETA'],
            'otrovehic': row['OTROVEHIC']
        }
        result = connection.execute(vehiculo.insert().values(vehiculo_insert))
        vehiculo_id = result.inserted_primary_key[0]

        # Insertar en la tabla causa_accidente
        causa_accidente_insert = {
            'causaacci': row['CAUSAACCI'],
            'caparod': row['CAPAROD']
        }
        result = connection.execute(causa_accidente.insert().values(causa_accidente_insert))
        causa_accidente_id = result.inserted_primary_key[0]

        # Insertar en la tabla victima
        victima_insert = {
            'id_edad': row['ID_EDAD'],
            'condmuerto': row['CONDMUERTO'],
            'condherido': row['CONDHERIDO'],
            'pasamuerto': row['PASAMUERTO'],
            'pasaherido': row['PASAHERIDO'],
            'peatmuerto': row['PEATMUERTO'],
            'peatherido': row['PEATHERIDO'],
            'ciclmuerto': row['CICLMUERTO'],
            'ciclherido': row['CICLHERIDO'],
            'otromuerto': row['OTROMUERTO'],
            'otroherido': row['OTROHERIDO'],
            'nemuerto': row['NEMUERTO'],
            'neherido': row['NEHERIDO']
        }
        result = connection.execute(victima.insert().values(victima_insert))
        victima_id = result.inserted_primary_key[0]

        # Insertar en la tabla accidente
        accidente_insert = {
            'id_tiempo': tiempo_id,
            'id_ubicacion': ubicacion_id,
            'id_vehiculo': vehiculo_id,
            'id_causa': causa_accidente_id,
            'id_victima': victima_id,
            'clasacc': row['CLASACC']
        }
        connection.execute(accidente.insert().values(accidente_insert))